### ISSUE TITLE
Tron LandResource Migration.

### ISSUE THREAD

**Issue by hujw77** [evolutionlandorg/land#61]
## Migration
To upgrade to furnace version. We could migrate the `LandResource` contract.

1. Create a new `LandResource` contract.
2. User call `stopMining` and `claimAllResource` on old contract.
3. User call `startMining` on new contract to complete migration.

## TODO
- [ ] Review `TokenUse` to ensure migration security.
- [ ] New `LandResource` may support proxy.
- [ ] One-Click migration contract support.  
- [ ] Frontend and Backend support.
